name: Prepare variable
on:
  workflow_call:
  
jobs:
  prepare-variable:
    runs-on: ubuntu-latest    
    outputs:
      APP_VERSION: ${{ steps.set_version.outputs.APP_VERSION }}
      ENV_SERVER: ${{ steps.set_env.outputs.ENV_SERVER }}
    steps:
      - name: Set version and environment
        id: set_environment
        run: |
          if [[ "${{ github.ref }}" == *"refs/heads/development"* ]]; then
            env_server="development"
            echo "ENV_SERVER=${env_server}" >> $GITHUB_OUTPUT
            echo "APP_VERSION=$(date +%Y.%m.%d)-${env_server}_${{ github.sha }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == *"refs/heads/staging"* ]]; then
            env_server="staging"
            echo "ENV_SERVER=${env_server}" >> $GITHUB_OUTPUT
            echo "APP_VERSION=$(date +%Y.%m.%d)-${env_server}_${{ github.sha }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == *"refs/tags/v*"* ]]; then
            env_server="production"
            echo "ENV_SERVER=${env_server}" >> $GITHUB_OUTPUT
            echo "APP_VERSION=$(date +%Y.%m.%d)-${env_server}_${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi
        
      - name: Variable validation
        id: validate_variables
        run: |
          echo "App Version: ${{ steps.set_environment.outputs.APP_VERSION }}"
          echo "Environment Server: ${{ steps.set_environment.outputs.ENV_SERVER }}"