name: Run workflows

on:
  workflow_call:

jobs:
  prepare-version:
    runs-on: ubuntu-latest
    outputs:
      APP_VERSION: ${{ steps.pre.outputs.APP_VERSION }}
      ENV_SERVER: ${{ steps.pre.outputs.ENV_SERVER }}
    steps:
      - name: Prepare Version and Environment
        uses: ./.github/actions/pre-build

  build-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Build Maven Application
        uses: ./.github/actions/mvn-build
    needs: prepare-version